// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD5ZxRLIUL0BH3_vlBUvCKsb6jR7KXaF4',
    appId: '1:1072160261169:web:31a480b2f3368918fb8110',
    messagingSenderId: '1072160261169',
    projectId: 'el-daftar-3ee0c',
    authDomain: 'el-daftar-3ee0c.firebaseapp.com',
    storageBucket: 'el-daftar-3ee0c.appspot.com',
    measurementId: 'G-9H5Q5XKCTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBseBL6fk8Z2i7V-xuU4NNXnm_LvyIXBww',
    appId: '1:1072160261169:android:7e69c87a808fdfabfb8110',
    messagingSenderId: '1072160261169',
    projectId: 'el-daftar-3ee0c',
    storageBucket: 'el-daftar-3ee0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn823Ox2k3x3GaC9NUN6WQzN_YxBpGUmQ',
    appId: '1:1072160261169:ios:b4cd5971aaac1ecffb8110',
    messagingSenderId: '1072160261169',
    projectId: 'el-daftar-3ee0c',
    storageBucket: 'el-daftar-3ee0c.appspot.com',
    iosBundleId: 'com.example.aldafttar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn823Ox2k3x3GaC9NUN6WQzN_YxBpGUmQ',
    appId: '1:1072160261169:ios:de9d9cab0a932bd3fb8110',
    messagingSenderId: '1072160261169',
    projectId: 'el-daftar-3ee0c',
    storageBucket: 'el-daftar-3ee0c.appspot.com',
    iosBundleId: 'com.example.aldafttar.RunnerTests',
  );
}
